Messages:
  Reloaded: "&eImageFrame has been reloaded!"
  ImageMapCreated: "&aImageMap has been created!"
  ImageMapRefreshed: "&aImageMap has been refreshed!"
  ImageMapDeleted: "&eImageMap had been deleted!"
  ImageMapRenamed: "&aImageMap had been Renamed!"
  UnableToLoadMap: "&cImageMap cannot be loaded, there is a problem while reading the image."
  NotAnImageMap: "&cThat is not an ImageMap"
  URLImageMapInfo:
    - "&bImageID: {ImageID}"
    - "&aName: {Name}"
    - "&eMap Size: {Width} x {Height}"
    - "&dCreator: {CreatorName} ({CreatorUUID})"
    - "&aTime Created: {TimeCreated}"
    - "&bMarkers: {Markers}"
    - "&eURL: {URL}"
  NoPermission: "&cYou do not have permission to do that!"
  NoConsole: "&cThis command can only be ran by players!"
  InvalidUsage: "&cInvalid Usage!"
  NotEnoughMaps: "&cYou do not have {Amount} maps!"
  Oversize: "&cThat is too big! Max size for a map is {MaxSize}"
  URLRestricted: "&cThat URL is restricted and cannot be used to create image maps."
  PlayerCreationLimitReached: "&cYou can only create <Limit> maps at once! Delete some to create new ones"
  DuplicateMapName: "&cYou've already created an image map with that name!"
  MapLookup: "&bList of image maps by {CreatorName} ({CreatorUUID}):"
  Selection:
    Begin: "&bRight click an Item Frame to select corner 1 and 2"
    Clear: "&eLeaving selection mode"
    Corner1: "&aSelected Item Frame corner 1"
    Corner2: "&aSelected Item Frame corner 2"
    Invalid: "&cInvalid selection!"
    Oversize: "&cOversize selection! Max size for a map is {MaxSize}"
    Success: "&aSelected {Width} x {Height} Item Frames! &eIf any of them are removed/replaced, you will need to select them again."
    NoSelection: "&cYou don't have a valid selection yet."
    IncorrectSize: "&cYour selection's size does not match, {Width} x {Height} required."
  Markers:
    AddBegin: '&aRight click on an Item Frame containing the map "{Name}" to place marker! &bRun "/imageframe marker cancel" to cancel placement'
    AddConfirm: "&aMarker placed!"
    Remove: "&eMarker removed!"
    Clear: "&eMarkers cleared!"
    Cancel: "&eMarker placement cancelled!"
    DuplicateName: "&cThere is already a marker with that name!"
    NotAMarker: "&cThat is not a valid marker"
    NotRenderOnFrameWarning: "&eWarning: This marker type does not render on Item Frames!"
    LimitReached: "&cYou can only create <Limit> markers on one map!"
  #Date format used where a time based variable is displayed
  DateFormat: "dd/MM/yyyy HH:mm:ss zzz"

Settings:
  MapItemFormat: "&f{Name} &7({X}, {Y})"
  #Whether empty maps are required to create image maps when not in creative
  RequireEmptyMaps: true
  #Max size of an image map
  MaxSize: 100
  #When enabled, Only websites from the list below is allowed to be shown through in-game maps
  RestrictImageUrl:
    Enabled: false
    Whitelist:
      - "https://i.imgur.com"
      - "http://i.imgur.com"
      - "https://storage.googleapis.com"
      - "http://storage.googleapis.com"
      - "https://cdn.discordapp.com"
      - "http://cdn.discordapp.com"
      - "https://media.discordapp.net"
      - "http://media.discordapp.net"
      - "https://textures.minecraft.net"
      - "http://textures.minecraft.net"
  #Max amount of image maps a player in the following groups can create
  #Setting -1 means unlimited
  #To add a player to a group, give the permission "imageframe.createlimit.<group>"
  #For example "imageframe.createlimit.vip"
  #Players with no groups will be treated as "default" unless they have "imageframe.createlimit.unlimited"
  PlayerCreationLimit:
    default: 10
    vip: 15
    moderator: 20
  #Max amount of markers on a individual map
  MapMarkerLimit: 20

#Enable update notifications for admins
Updater: true